<?$item = $this->item;
$this->headTitle($item->Name)->headTitle('Мир аниме Смотреть Аниме Онлайн Anime online бесплатно');
?>
<div class="item single">
    <h2><?=$item->Name?> (<?=count($this->parts)?> из <?=$item->TotalParts?:'. . .'?>)</h2>
    <?if($this->isAdmin){?>
        <a href="/admin/edit-item/id/<?=$item->Id?>" title="Редактировать" class="edit"></a>
        <a href="/admin/delete-item/id/<?=$item->Id?>" title="Удалить" class="delete"></a>
    <?}?>
    <a class="item_pic" href="#"><img src="/img/anime/<?=$item->Image?>"/></a>
    <article><?=$item->Description?></article>
    <?=$this->object?>
    <span>Серия: </span>
    <select id="part">
        <?foreach($this->parts as $part){?>
            <option <?=$this->part == $part->Part?'selected':''?> value="<?=$part->Part?>"><?=$part->Name?> (<?=$part->Part?> серия)</option>
        <?}?>
    </select>

    <!-- Put this div tag to the place, where the Comments block will be -->
    <div id="vk_comments"></div>
    <script type="text/javascript">
        VK.Widgets.Comments("vk_comments", {limit: 5, width: "520", attach: "*"});
    </script>
</div>
