<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="resourse-type" content="document">
    <meta name="document-state" content="dynamic">
    <meta name="revisit-after" content="2 days">
    <meta name="robots" content="ALL">
    <?$this->headMeta()->setName('description', isset($this->title)?$this->title:'Смотреть аниме онлайн anime online')
        ->setHttpEquiv('description', isset($this->title)?$this->title:'Смотреть аниме онлайн anime online')
        ->setName('keywords', isset($this->title)?$this->title:'Смотреть аниме онлайн anime online')
        ->setHttpEquiv('keywords', isset($this->title)?$this->title:'Смотреть аниме онлайн anime online')?>
    <?=$this->headMeta() ?>
    <?=$this->headTitle()?>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <link rel="stylesheet" href="/css/main.css"/>
    <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
    <script src="/js/main.js" type="text/javascript"></script>
    <!-- Put this script tag to the <head> of your page -->
    <script type="text/javascript" src="//vk.com/js/api/openapi.js?111"></script>

    <script type="text/javascript">
        VK.init({apiId: 4321104, onlyWidgets: true});
    </script>
</head>
<body>
<h1 class="describe"><?=isset($this->title)?$this->title:'Смотреть аниме онлайн anime online'?></h1>
<header>
    <a href="/" title="Anime world"><img class="logo" src="/img/logo.png" alt="Anime World"/></a>
    <a id="rand_item" href="/<?=($this->randomItem->Type == 1?'anime/movie':'manga/story').'/id/'.$this->randomItem->Id?>" title="<?=$this->randomItem->Name?>">
        <img src="/img/<?=($this->randomItem->Type == 1?'anime/':'manga/').$this->randomItem->Image?>"/>
    </a>
</header>
<div id="wrapper">
    <ul id="menu">
        <li><a href="/">Главная</a></li>
        <li><a href="/anime">Аниме</a></li>
        <li><a href="/anime/index<?=isset($this->genre)?'/genre/'.$this->genre:''?>/sort/popular">Популярные</a></li>
        <?if($this->isAdmin){?><li><a href="/manga">Манга</a></li>
        <li><a href="/admin/add-item">Добавить материал</a></li><?}?>
    </ul>
    <div id="left_col">
        <?if(isset($this->genres)){?>
        <ul class="menu_genres l_menu">
            <?
            $i = 0;
            foreach($this->genres as $genre){?>
            <li>
                <a class="<?=$genre->Id == $this->genre?'active':''?>" href="<?=$this->url(array('module' => Zend_Controller_Front::getInstance()->getRequest()->getModuleName(), 'controller' =>Zend_Controller_Front::getInstance()->getRequest()->getControllerName(), 'action' => 'index','genre' => $genre->Id),null,true)?>"><?=$genre->Name?></a>
            </li>
                <?if((++$i)%10 == 0){?></ul><ul class="menu_genres l_menu"><?}?>
            <?}?>
        </ul>
        <?}else{?>
        <ul id="l_menu">
            <li><a href="/anime">Аниме</a></li>
            <li><a href="/manga">Манга</a></li>
        </ul>
        <?}?>
    </div>
    <div id="right_col">
        <?if(!$this->auth->hasIdentity()){?>
            <a href="#" id="login_button"><img src="/img/vklogin.png"/></a>
        <?}else{?>
            <img width="20" src="<?=$this->auth->getIdentity()->User->Photo?>"/>
            <span><?=$this->auth->getIdentity()->User->Name?></span>
            <a href="/auth/logout" title="Выйти">-></a>
        <?}?>
        <form id="search" method="post"><input type="text" name="search" placeholder="Поиск"/><img src="/img/search.gif" title="Искать"/></form>
        <div class="promo">
            <!-- Поместите этот тег туда, где должна отображаться кнопка +1. -->
            <div class="g-plusone"></div>

            <!-- Поместите этот тег за последним тегом виджета кнопка +1. -->
            <script type="text/javascript">
                window.___gcfg = {lang: 'ru'};

                (function() {
                    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                    po.src = 'https://apis.google.com/js/platform.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
                })();
            </script>
            <!-- Put this script tag to the <head> of your page -->
            <script type="text/javascript" src="http://vk.com/js/api/share.js?90" charset="windows-1251"></script>

            <!-- Put this script tag to the place, where the Share button will be -->
            <script type="text/javascript"><!--
                document.write(VK.Share.button(false,{type: "round", text: "Сохранить"}));
                --></script>
            <a target="_blank" class="mrc__plugin_uber_like_button" href="http://connect.mail.ru/share" data-mrc-config="{'cm' : '1', 'sz' : '20', 'st' : '2', 'tp' : 'mm'}">Нравится</a>
            <script src="http://cdn.connect.mail.ru/js/loader.js" type="text/javascript" charset="UTF-8"></script>

            <!--www.people-group.net-->
            <script async src="//ads.people-group.net/171747/1/1/1/" onload="InitAipg_17174700010001(this)"></script>
            <!--www.people-group.net-->
            <!--www.people-group.net-->
            <script async src="//ads.people-group.net/171747/1/2/1/" onload="InitAipg_17174700010002(this)"></script>
            <!--www.people-group.net-->

        </div>
    </div>
    <div id="content">
        <div class="scrolling">
            <?=$this->layout()->content;?>
        </div>
    </div>
    <footer>
        <div>Внимание сайт содержит материалы для взрослых. Все материалы на этом сайте продублированы из источников свободного распространения и предназначено только для домашнего ознакомления. Все права на представленные материалы принадлежат их авторам. Администрация сайта не несёт ответственности за представленный материал и его любое использование. Если какой-нибудь из представленных материалов нарушает ваши авторские права, то просим вас незамедлительно связаться с нами и мы удалим этот материал с ресурса!</div>
    </footer>
</div>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-50328942-1', 'ani-world.ru');
    ga('send', 'pageview');

</script>
<!-- Yandex.Metrika informer -->
<a href="https://metrika.yandex.ru/stat/?id=24783713&amp;from=informer"
   target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/24783713/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
                                       style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:24783713,lang:'ru'});return false}catch(e){}"/></a>
<!-- /Yandex.Metrika informer -->

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter24783713 = new Ya.Metrika({id:24783713,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/24783713" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
<!-- Rating@Mail.ru counter -->
<script type="text/javascript">
    var _tmr = _tmr || [];
    _tmr.push({id: "2506795", type: "pageView", start: (new Date()).getTime()});
    (function (d, w) {
        var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true;
        ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
        var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
        if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
    })(document, window);
</script><noscript><div style="position:absolute;left:-10000px;">
        <img src="//top-fwz1.mail.ru/counter?id=2506795;js=na" style="border:0;" height="1" width="1" alt="Рейтинг@Mail.ru" />
    </div></noscript>
<!-- //Rating@Mail.ru counter -->

<!-- Обратная связь -->
<div id="send_message">
    <?=$this->action('index', 'message'); ?>
</div>
<!-- //Обратная связь -->
</body>
</html>