<form method="post" action="/admin/anime-parser">
    Автодобавление: <input type="url" name="url"/>
    <input type="submit" value="Добавить"/>
</form>
<br/>
<hr/>
<form method="post" action="/admin/parse-all">
    Все аниме c сайтa: <input type="url" name="url"/>
    <input type="submit" value="Добавить"/>
</form>
<br/>
<hr/>
<br/>
<form method="post" enctype="multipart/form-data">
    <table>
    <?foreach($this->fields as $name => $field){
        if($field['PRIMARY'] || $name == 'Date') continue;
        ?>
        <tr>
            <td><label for="<?=$name?>"><?=$name?>: </label></td>
            <td>
                <?switch($field['DATA_TYPE']){
                    case 'text':
                        print "<textarea required id='$name' name='$name'></textarea>";
                        break;
                    case 'tinyint':
                        if($name == 'Type'){
                            print "<select required id='$name' name='$name'>";
                            print "<option value='1'>Аниме</option>";
                            print "<option value='2'>Манга</option>";
                            print "<option value='3'>Новость</option>";
                            print "</select>";
                        }else{
                            "<input type='checkbox' id='$name' name='$name'/>";
                        }
                        break;
                    default:
                        if($name == 'Image'){
                            print "<input required type='file' id='$name' name='$name'/>";
                        }else{
                            print "<input required type='text' id='$name' name='$name' value='$field[DEFAULT]'/>";
                        }
                        break;
                }?>
            </td>
        </tr>
    <?}?>
        <tr>
            <td>Жанры: </td>
            <td>
                <?foreach($this->genres as $genre){?>
                    <input id="genre_<?=$genre->Id?>" type="checkbox" name="Genres[<?=$genre->Id?>]" value="<?=$genre->Id?>"/>
                    <label for="genre_<?=$genre->Id?>"><?=$genre->Name?></label>
                    <br/>
                <?}?>
            </td>
        </tr>
    </table>
    <input type="submit" value="Сохранить"/>
</form>